### ISSUE TITLE
Composite Monitor Integration Tracker Meta

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#219]
- [x] https://github.com/opensearch-project/security-analytics/issues/220
- [x] https://github.com/opensearch-project/security-analytics/issues/222
- [x] https://github.com/opensearch-project/security-analytics/issues/225
- [x] https://github.com/opensearch-project/security-analytics/issues/226

**Comment by eirsep** [comment]
Feature branch for Common Utils package with Composite Monitor changes: [feature/composite-monitor](https://github.com/opensearch-project/common-utils/tree/feature/composite-monitor)

**Comment by stevanbz** [comment]
I created one PR for all the tickets listed above:
https://github.com/opensearch-project/security-analytics/pull/316

This PR is made against the [branch](https://github.com/opensearch-project/security-analytics/tree/feature/composite-monitor) - @eirsep and me agreed that we are going to use like "development" branch for composite monitors.

The main idea followed was that once the new detectors are being created, the workflow with delegate monitors will be created.

**Comment by engechas** [comment]
This functionality is implemented. Closing
