### ISSUE TITLE
[Meta] Security Analytics Custom Log Types support

### ISSUE THREAD

**Issue by petardz** [opensearch-project/security-analytics#459]
linked issue #447 

Tasks:

- [ ] 1. Define new LogType(JSON) structure which holds log type's _name_, _description_ and _field mappings_. For pre-packaged rules there should be set of files(1 file per log type) stored on disk. On Security Analytics startup, load these files into system index: `.opensearch-sap-log-types-config`.

- [ ] 2. User-defined(Custom) log types. Provide CRUD API for user to define its own custom log type. Custom log type will be defined by new LogType structure defined in first task and stored in `.opensearch-sap-log-types-config` index. Replace DetectorType enum with class which loads detector types(log types) from `.opensearch-sap-log-types-config`.

- [ ] 3. Modify existing Mappings APIs to utilize new JSON structure defined in first task, instead of mapping.json files.

- [ ] 4. Implement auto-detection of mapping schema(ECS, OCSF) used in log index.

**Comment by ict-one-nl** [comment]
Full ECS support would be nice as well. When trying to load the whole ECS schema component templates a couple of weeks ago Opensearch didn't support a couple of field types.

**Comment by DarshitChanpura** [comment]
@getsaurabh02 Should this be marked for 2.11?

**Comment by amsiglan** [comment]
Added support for custom log types in 2.10
