### ISSUE TITLE
[META] Rule curation layer(P0) & Rule ingestion layer(P0)

### ISSUE THREAD

**Issue by sbcd90** [opensearch-project/security-analytics#5]
**Is your feature request related to a problem?**

One of the important features of a Security Analytics solution is to define a mechanism to ingest & store security related rules into it. As of today, Sigma provides a comprehensive set of security related rules which can be used to identify threats. Sigma also provides a well-defined generic schema for defining new Sigma rules.

In order to reuse the existing set of Sigma rules & to support the existing Sigma schema, a Rule curation layer is required, which transforms, converts & aggregates Sigma rules into Opensearch queries. A Rule ingestion layer is required to ingest these queries into Opensearch.

**What solution would you like?**
There are 2 approaches considered for designing the Rule curation layer.

- A separate Opensearch specific Sigma backend converter

In this approach, the user needs to manually run the Opensearch backend converter to convert the rule yaml file defined using Sigma schema into Opensearch query & provide it as input to the plugin.

- A built-in Sigma rule parser

In this approach, the user just provides the rule yaml file defined using Sigma schema & the plugin takes care of converting the rule yaml into Opensearch query & finally ingest these queries into Opensearch.
This approach is especially beneficial for defining ad-hoc Sigma rules & allows users without Opensearch query syntax knowledge to also use this tool.
The `P1 Item Rule Editor Framework` is not possible without this approach.

**Do you have any additional context?**

The overall scope of MVP is defined [Security Analytics in OpenSearch (MVP)](https://github.com/opensearch-project/security-analytics/issues/7)

**Tasks**

- [X] integrate sigma rules-types, exeptions, utils
- [ ] integrate sigma rules-modifiers, conditions
- [ ] integrate sigma rules-objects, query backends
